*** set more off
**
**

set more off
insheet using "FILEPATH",clear
cap drop if outlier==1

cap drop logcumulative_infected logcumulative_infections
destring logdeath_rate_covid annual_pop_2020,force replace

lasso2 logdeath_rate_excess prop_pop_75plus mobility_lagged idr_lagged logcrude_death_rate logcumulative_infections_lagged crude_death_rate_sd_1990 avg_abs_latitude universal_health_coverage gbd_diabetes logdiabetes_death_rate gbd_inpatient_admis stars_binhigh gbd_obesity haqi hypertension_prevalence logckd logcong_downs logcvd_death_rate logendo loghemog_sickle loghemog_thalass loghiv logncd logneo logneuro logresp_asthma logresp_copd logsubs smoking_prevalence logdeath_rate_covid
lasso2, ic(aic) long
lasso2, lic(aic)

reg logdeath_rate_excess logcumulative_infections_lagged
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate loghiv_death_rate
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate loghiv_death_rate logdiabetes_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate loghiv_death_rate idr_lagged
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate loghiv_death_rate idr_lagged universal_health_coverage
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage loghiv_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh loghemog_sickle_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logsubs_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logcvd_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logresp_asthma_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis gbd_obesity
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logendo_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis prop_pop_75plus
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis loghemog_thalass_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis smoking_prevalence
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logresp_copd_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logneo_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis mobility_lagged
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logneuro_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logcong_downs_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logcvd_death_rate
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis avg_abs_latitude
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logckd_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis haqi
**ns
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logncd_death_rate
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis gbd_diabetes
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis hypertension_prevalence
**ws
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis


*** final model with significant covariates

reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence mobility_lagged
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence mobility_lagged avg_abs_latitude
reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence mobility_lagged avg_abs_latitude haqi


** Final model

reg logdeath_rate_excess logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence mobility_lagged avg_abs_latitude haqi


reg logdeath_rate_excess

logcumulative_infections_lagged logdeath_rate_covid logcrude_death_rate idr_lagged universal_health_coverage stars_binhigh gbd_inpatient_admis logdiabetes_death_rate loghiv_death_rate logcvd_death_rate prop_pop_75plus smoking_prevalence mobility_lagged avg_abs_latitude haqi
